In [1]:
!git clone https://github.com/OPnitesh/PYTORCH.git

Cloning into 'PYTORCH'...


In [ ]:
import torch
print(torch.__version__)

In [2]:
t1=torch.tensor(4.)
t1

tensor(4.)

In [3]:
t1.dtype

torch.float32

In [4]:
# vector
t2=torch.tensor([1.,2,3,4])
t2

tensor([1., 2., 3., 4.])

In [6]:
#matrix
t3=torch.tensor([[5.,6.],
                [7.,8.],
                 [9.,10.]])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [13]:
# 3d-dimensional
t4=torch.tensor([
                  [[11,12,13],
                  [13,14,15]],
                  [[15,16,17],
                  [17,18,19]]])
t4

tensor([[[11, 12, 13],
         [13, 14, 15]],

        [[15, 16, 17],
         [17, 18, 19]]])

In [9]:
t1.shape

torch.Size([])

In [15]:
t3.shape

torch.Size([3, 2])

In [14]:
t4.shape

torch.Size([2, 2, 3])

Tensor operation and gradient

In [16]:
## create tensors.
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)
x, w, b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

we have created three tensor: x w b all number w and b have an additional parameters require_grad set to true.

lets create a new tensor y by combinning these tensors

In [17]:
y=w*x+b
y

tensor(17., grad_fn=<AddBackward0>)

In [18]:
# compute the derivative
y.backward()

In [19]:
## display the gradient
print('dy/dx', x.grad) ## it getting none becz it does't hold the gradient=true.
print('dy/dw', w.grad)
print('dy/db', b.grad)

dy/dx None
dy/dw tensor(3.)
dy/db tensor(1.)


Tensor Function

In [22]:
t6=torch.full([3,2], 42)
t6

tensor([[42, 42],
        [42, 42],
        [42, 42]])

In [23]:
## concate the tensors with the two compatible shapes
t7=torch.cat([t3,t6])
t7

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [42., 42.],
        [42., 42.],
        [42., 42.]])

In [24]:
#compute the sin of each element
t8=torch.sin(t7)
t8

tensor([[-0.9589, -0.2794],
        [ 0.6570,  0.9894],
        [ 0.4121, -0.5440],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165]])

In [28]:
## change the shape of tensors
t9=t8.reshape(2,3,2)
t9

tensor([[[-0.9589, -0.2794],
         [ 0.6570,  0.9894],
         [ 0.4121, -0.5440]],

        [[-0.9165, -0.9165],
         [-0.9165, -0.9165],
         [-0.9165, -0.9165]]])

Linear-regression from scratch using pytorch

In [72]:
import numpy as np
import torch

In [73]:
# making taining data
# input (temp, rainfall, humidity)
input = np.array([[73, 67, 43],
                  [91, 88, 64],
                  [87, 134, 58],
                  [102, 43, 37],
                  [69, 96, 70]], dtype='float32')

In [74]:
# targets (apple, oranges)
target = np.array([[56, 70],
                   [81, 101],
                   [119, 133],
                   [22, 37],
                   [103, 119]], dtype='float32')

In [75]:
# convert input and target to tensors
inputs  = torch.from_numpy(input)
targets = torch.from_numpy(target)

print(inputs,"\n")
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]]) 

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [76]:
# weights and biases
w = torch.randn(2,3, requires_grad=True)
b = torch.randn(2, requires_grad=True)

print(w)
print(b)


tensor([[ 0.8579, -0.7527,  1.5819],
        [-0.9530, -1.4692,  1.1312]], requires_grad=True)
tensor([1.8834, 1.5916], requires_grad=True)


In [77]:
# define the model and @ represent matrix mul:
#w.t() is the transpose of the weight matrics.
def model(x):
  return x @ w.t() + b

In [78]:
# prediction
preds = model(inputs)
print(preds)

tensor([[  82.0994, -117.7754],
        [ 114.9545, -142.0284],
        [  67.4092, -212.5850],
        [ 115.5498, -116.9407],
        [  99.5518, -126.0277]], grad_fn=<AddBackward0>)


In [79]:
# actuall
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [80]:
# loss function MSE
def MSE(actual,targets):
  diff = actual - targets
  return torch.sum(diff*diff) / diff.numel()


In [81]:
# error
loss = MSE(targets, preds)
print(loss)

tensor(31074.6875, grad_fn=<DivBackward0>)


In [82]:
# compute the gradient
loss.backward()


In [83]:
print(w, "\n")
print(w.grad)

tensor([[ 0.8579, -0.7527,  1.5819],
        [-0.9530, -1.4692,  1.1312]], requires_grad=True) 

tensor([[  1962.1754,    303.0227,    704.6140],
        [-19699.5879, -22083.5918, -13303.9668]])


In [84]:
print(b, "\b")
print(b.grad)

tensor([1.8834, 1.5916], requires_grad=True) 
tensor([  19.7130, -235.0714])


In [85]:
# reset grad to iterate and and adjust the parameter
w.grad.zero_()
b.grad.zero_()

print(w.grad)

print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


In [86]:
# adjust params
preds = model(inputs)
print(preds)

tensor([[  82.0994, -117.7754],
        [ 114.9545, -142.0284],
        [  67.4092, -212.5850],
        [ 115.5498, -116.9407],
        [  99.5518, -126.0277]], grad_fn=<AddBackward0>)


In [87]:
# losss
loss = MSE(targets, preds)
print(loss)

tensor(31074.6875, grad_fn=<DivBackward0>)


In [89]:
loss.backward()

print(w.grad,"\n")
print(b.grad)

tensor([[  1962.1754,    303.0227,    704.6140],
        [-19699.5879, -22083.5918, -13303.9668]]) 

tensor([  19.7130, -235.0714])


In [90]:
# adjust weight & reset grad
with torch.no_grad():
  w-=w.grad* 1e-5
  b-=b.grad* 1e-5
  w.grad.zero_()
  b.grad.zero_()

In [91]:
print(w)
print(b)

tensor([[ 0.8382, -0.7557,  1.5748],
        [-0.7561, -1.2483,  1.2642]], requires_grad=True)
tensor([1.8832, 1.5939], requires_grad=True)


In [93]:
# calculate again
preds= model(inputs)
loss= MSE(targets, preds)
print(loss)

tensor(21447.2910, grad_fn=<DivBackward0>)


In [97]:
# trainig for multiple epochs
for i in range(400):
  preds = model(inputs)
  loss= MSE(targets,preds)
  loss.backward()

  with torch.no_grad():
    w-=w.grad*1e-5
    b-=b.grad*1e-5
    w.grad.zero_()
    b.grad.zero_()
  print(f"EPOCHS({i}/{100}) & Loss {loss}")

EPOCHS(0/100) & Loss 21447.291015625
EPOCHS(1/100) & Loss 3115.14306640625
EPOCHS(2/100) & Loss 2576.42236328125
EPOCHS(3/100) & Loss 2207.7822265625
EPOCHS(4/100) & Loss 1953.8265380859375
EPOCHS(5/100) & Loss 1777.224365234375
EPOCHS(6/100) & Loss 1652.817626953125
EPOCHS(7/100) & Loss 1563.65283203125
EPOCHS(8/100) & Loss 1498.302490234375
EPOCHS(9/100) & Loss 1449.0667724609375
EPOCHS(10/100) & Loss 1410.7548828125
EPOCHS(11/100) & Loss 1379.868896484375
EPOCHS(12/100) & Loss 1354.0498046875
EPOCHS(13/100) & Loss 1331.7081298828125
EPOCHS(14/100) & Loss 1311.771240234375
EPOCHS(15/100) & Loss 1293.515869140625
EPOCHS(16/100) & Loss 1276.453857421875
EPOCHS(17/100) & Loss 1260.2552490234375
EPOCHS(18/100) & Loss 1244.6966552734375
EPOCHS(19/100) & Loss 1229.6279296875
EPOCHS(20/100) & Loss 1214.946044921875
EPOCHS(21/100) & Loss 1200.58154296875
EPOCHS(22/100) & Loss 1186.486083984375
EPOCHS(23/100) & Loss 1172.627685546875
EPOCHS(24/100) & Loss 1158.982666015625
EPOCHS(25/100) & Lo

In [98]:
preds = model(inputs)
loss = MSE(targets,preds)
print(loss)

tensor(66.3408, grad_fn=<DivBackward0>)


In [99]:
from math import sqrt
sqrt(loss)

8.144986498068056

In [100]:
preds

tensor([[ 58.0239,  70.5234],
        [ 88.1537, 106.3848],
        [103.7933, 119.6219],
        [ 24.7945,  37.2687],
        [110.4682, 129.2467]], grad_fn=<AddBackward0>)

In [101]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

Neural Network using pytorch

In [1]:
# to check gpu
!nvidia-smi


Sun Mar  3 11:18:28 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   36C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [5]:
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets
from torchvision.transforms import ToTensor, Lambda, Compose
import matplotlib.pyplot as plt



In [6]:
# download trainig data from open datasets.
training_data = datasets.FashionMNIST(
     root = "data",
     train=True,
     download=True,
     transform=ToTensor(),
 )
# download test data from open datasets.
test_data = datasets.FashionMNIST(
    root = "data",
    train=False,
    download=True,
    transform=ToTensor(),
)


100%|██████████| 26421880/26421880 [00:01<00:00, 14938822.23it/s]


Extracting data/FashionMNIST/raw/train-images-idx3-ubyte.gz to data/FashionMNIST/raw



100%|██████████| 29515/29515 [00:00<00:00, 270707.66it/s]


Extracting data/FashionMNIST/raw/train-labels-idx1-ubyte.gz to data/FashionMNIST/raw



100%|██████████| 4422102/4422102 [00:00<00:00, 5003756.70it/s]


Extracting data/FashionMNIST/raw/t10k-images-idx3-ubyte.gz to data/FashionMNIST/raw



100%|██████████| 5148/5148 [00:00<00:00, 5165616.51it/s]

Extracting data/FashionMNIST/raw/t10k-labels-idx1-ubyte.gz to data/FashionMNIST/raw



In [7]:
type(training_data)

torchvision.datasets.mnist.FashionMNIST

In [8]:
batch_size = 64

# create data loaders
train_dataloader = DataLoader(training_data, batch_size=batch_size)
test_dataloader = DataLoader(test_data, batch_size=batch_size)

for X, y in test_dataloader:
  print("shape of x [N, C, H, W] : ", X.shape)
  print("shape of y: ", y.shape, y.dtype)
  #print(X)
  #print(y)
  break

shape of x [N, C, H, W] :  torch.Size([64, 1, 28, 28])
shape of y:  torch.Size([64]) torch.int64


In [9]:
# get cpu or gpu device for training .
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using {device} device")

Using cuda device


In [10]:
# define model
class NeuralNetwork(nn.Module):
  def __init__(self):
    super(NeuralNetwork, self).__init__()
    self.flatten = nn.Flatten()
    self.linear_relu_stack = nn.Sequential(
        nn.Linear(28*28, 512),
        nn.ReLU(),
        nn.Linear(512, 512),
        nn.ReLU(),
        nn.Linear(512, 10)
    )
  def forward(self, x):
    x = self.flatten(x)
    logits = self.linear_relu_stack(x)
    return logits
model = NeuralNetwork().to(device)
print(model)


NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)


In [11]:
loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model.parameters(), lr=1e-3)

In [12]:
def train(dataloader, model, loss_fn, optimizer):
  size = len(dataloader.dataset)
  model.train()
  for batch, (X, y) in enumerate(dataloader):
    X, y = X.to(device), y.to(device)

    # compute prediciton error
    pred = model(X)
    loss = loss_fn(pred,y)

    ## backpropagation
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if batch % 100 ==0:
       loss, current = loss.item(), batch*len(X)
       print(f"loss: {loss:>7f} [{current:>5d}/{size:>5d}]")

In [13]:
def test(dataloader, model, loss_fn):
  size = len(dataloader.dataset)
  num_batches = len(dataloader)
  model.eval()
  test_loss, correct = 0, 0
  with torch.no_grad():
    for X, y in dataloader:
      X, y = X.to(device), y.to(device)
      pred = model(X)
      test_loss+= loss_fn(pred, y).item()
      correct+= (pred.argmax(1) == y).type(torch.float).sum().item()
    test_loss /= num_batches
    correct /= size
    print(f"test error: \n accuracy: {(100*correct):>0.1f}%, avg loss: {test_loss:>8f}  \n")


In [14]:
epochs = 5
for t in range(epochs):
  print(f"epochs {t+1} \n------------------------")
  train(train_dataloader, model, loss_fn, optimizer)
  test(test_dataloader, model, loss_fn)
print("Done!!")

epochs 1 
------------------------
loss: 2.313877 [    0/60000]
loss: 2.301392 [ 6400/60000]
loss: 2.287796 [12800/60000]
loss: 2.273641 [19200/60000]
loss: 2.245208 [25600/60000]
loss: 2.228336 [32000/60000]
loss: 2.242168 [38400/60000]
loss: 2.208712 [44800/60000]
loss: 2.200169 [51200/60000]
loss: 2.170342 [57600/60000]
test error: 
 accuracy: 35.2%, avg loss: 2.165783  

epochs 2 
------------------------
loss: 2.176294 [    0/60000]
loss: 2.171599 [ 6400/60000]
loss: 2.123012 [12800/60000]
loss: 2.135499 [19200/60000]
loss: 2.082360 [25600/60000]
loss: 2.025422 [32000/60000]
loss: 2.067966 [38400/60000]
loss: 1.985907 [44800/60000]
loss: 1.987984 [51200/60000]
loss: 1.933740 [57600/60000]
test error: 
 accuracy: 52.8%, avg loss: 1.924941  

epochs 3 
------------------------
loss: 1.946632 [    0/60000]
loss: 1.935398 [ 6400/60000]
loss: 1.827363 [12800/60000]
loss: 1.870585 [19200/60000]
loss: 1.765755 [25600/60000]
loss: 1.700105 [32000/60000]
loss: 1.744616 [38400/60000]
loss: 

In [15]:
# save model
torch.save(model.state_dict(), "model.pth")
print("saved pytorch model state to model.pth")

saved pytorch model state to model.pth


In [16]:
# load model  (yaha per agar hume data set or koi mille to bs apne save kiye hue data ko lena hae and ussi pe train karna hae)
model = NeuralNetwork()
model.load_state_dict(torch.load("model.pth"))

<All keys matched successfully>

In [17]:
#### prediction
classes = [
    "T-shirt/top",
    "Trouser",
    "Pullover",
    "Dress",
    "Coat",
    "Sandal",
    "Shirt",
    "Sneaker",
    "Bag",
    "ankle boot",
]

model.eval()
x, y = test_data[0][0], test_data[0][1]
with torch.no_grad():
  pred = model(x)
  predicted, actual = classes[pred[0].argmax(0)], classes[y]
  print(f'Predicted: "{predicted}", actual: "{actual}"')

Predicted: "ankle boot", actual: "ankle boot"
